all: test

CXXFLAGS = -W -Wall -O -g -I. -I../ -I../../ -std=c++17

EXTRA_OBJS = \
    ../../AK/StringImpl.o \
    ../../AK/String.o \
    ../../AK/StringBuilder.o \
    ../../AK/StringView.o

include Makefile.shared

test: $(OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(OBJS)
